version : '3.8'
services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    image: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure
            
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    image: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/fouaouri/data/wordpress'

  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/fouaouri/data/mariadb'

networks:
  inception:
    name: inception
