version : '3'
services:
  nginx:
    build: nginx
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure
            
  mariadb:
    build: mariadb
    container_name: mariadb
    networks:
      - inception
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  wordpress:
    build: wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure
    expose: 
      - "9000"


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/fouaouri/data/wordpress'

  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/fouaouri/data/mariadb'

networks:
  inception:
    name: inception
